#ifndef _M4_IDL_
#define _M4_IDL_

#pragma prefix "MarpaX::Languages"
module M4
{

  typedef sequence <string> stringArray;

  interface builtins {
    string define(in string name, in string expansion);
    string undefine(in stringArray names);
    string defn(in stringArray names);
    string pushdef(in string name, in string expansion);
    string popdef(in stringArray names);
    string indir(in string name, in stringArray args);
    string builtin(in string name, in stringArray args);
    string ifdef(in string name, in string string1, in string string2);
    string ifelse(in stringArray args);
    string shift(in stringArray args);
    string dumpdef(in stringArray names);
    string traceon(in stringArray names);
    string traceoff(in stringArray names);
    string debugmode(in string flags);
    string debugfile(in string file);
    string dnl(in string args);
    string changequote(in string start, in string end);
    string changecom(in string start, in string end);
    string changeword(in string regexp);
    string m4wrap(in string string, in stringArray others);
    string include(in string file);
    string sinclude(in string file);
    string divert(in string number);
    string undivert(in stringArray diversions);
    string divnum();
    string len(in string string);
    string index(in string string, in string substring);
    string regexp(in string string, in string regexp, in string replacement);
    string substr(in string string, in string from, in string length);
    string translit(in string string, in string chars, in string replacement);
    string patsubst(in string string, in string regexp, in string replacement);
    string format(in string formatString, in stringArray args);
    string incr(in string number);
    string decr(in string number);
    string eval(in string expression, in string radix);
    /* string __gnu__(); */         /* Optional */
    /* string __os2__(); */         /* Optional */
    /* string os2(); */             /* Optional */
    /* string __unix__(); */        /* Optional */
    /* string unix(); */            /* Optional */
    /* string __windows__(); */     /* Optional */
    string windows();
    string syscmd(in string shellCommand);
    string esyscmd(in string shellCommand);
    string sysval();
    string mkstemp(in string template);
    string maketemp(in string template);
    string errprint(in string message, in stringArray rest);
    string __file__();
    string __line__();
    string __program__();
  };
};

#endif // _M4_IDL_
